from typing import Protocol
from ludus.schemas import StepRecord, EpisodeResult


class Store(Protocol):
    def save_screenshot(self, episode_id: str, step_index: int, png: bytes) -> str: ...
    def save_step(self, step: StepRecord) -> None: ...
    def save_episode(self, result: EpisodeResult) -> None: ...
